//
// Created by thomas on 27/02/20.
//

#ifndef PLUGINIZED_BIRD_UBPF_API_COMMON_H
#define PLUGINIZED_BIRD_UBPF_API_COMMON_H

#define RTE_NEW 0
#define RTE_OLD 1
#define RTE_UNK 2
#define FAIL 3

#define PLUGIN_FILTER_ACCEPT 0
#define PLUGIN_FILTER_REJECT 1
#define PLUGIN_FILTER_UNK 2

#define IANA_UNNASIGNED 41

#define MED_ATTR 4
#define BA_GEO_TAG 0x2a ## u
#define PREFIX_ORIGINATOR 0x2b
#define ROUTER_ANNOUNCER_COORDINATE 0x2c

#define IANA_MAX_UNASIGNED 127

#endif //PLUGINIZED_BIRD_UBPF_API_COMMON_H
